import { useState, useEffect } from 'react';
// @ts-ignore: CSS module declarations not available in this project
import './Instructor.css';
import toast from 'react-hot-toast';
import { useAuth } from '../../context/AuthContext';
import type { Course } from '../../types/interfaces';
import { useForm, useFieldArray } from 'react-hook-form';
import { API_URL } from '../../constants';

const initialCourseState = {
  name: '',
  imageUrl: '',
  Duration: '',
  level:'',
  price: '',
  rating: '',
  description: '',
  chapters: []
};

const InstructorCourses =()=> {
  const [courses, setCourses] = useState<Course[]>([]);
  const [isEditing, setIsEditing] = useState<number | null>(null);
  const { currentUser } = useAuth();
  const { register, handleSubmit, reset, control, formState: { errors } } = useForm<Omit<Course, 'courseId'>>({ defaultValues: initialCourseState });

  const { fields, append, remove } = useFieldArray({
    control,
    name: "chapters"
  });

  useEffect(() => {
    if (currentUser?.userId && currentUser?.role === 'instructor') {
      fetchCourses();
    }
  }, [currentUser]);

  const fetchCourses = async () => {
    try {
      // Use query parameter to find courses generated by THIS instructor
      const res = await fetch(`${API_URL}/courses?userId=${currentUser?.userId}`);
      const data = await res.json();
      setCourses(data);
    } catch (error) {
      toast.error("Failed to fetch courses");
    }
  };

  const onSubmit = async (data: Omit<Course, 'courseId'>) => {
    if (isEditing || data?.courseId) {
      try {
        const res = await fetch(`${API_URL}/courses/${data?.courseId}?userId=${currentUser?.userId}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(data)
        });
        if (res.ok) {
          toast.success("Course updated successfully");
          fetchCourses();
          resetForm();
        }
      } catch (error) {
        toast.error("Failed to update course");
      }
    } else {
      try {
        const res = await fetch(`${API_URL}/courses/?userId=${currentUser?.userId}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(data)
        });
        if (res.ok) {
          toast.success("Course added successfully");
          fetchCourses();
          resetForm();
        }
      } catch (error) {
        toast.error("Failed to add course");
      }
    }
  };

  const handleEdit = (course: Course) => {
    setIsEditing(course.courseId);
    const { ...rest } = course;
    reset(rest);
    window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Are you sure you want to delete this course?")) return;

    try {
      const res = await fetch(`${API_URL}/courses/?userId=${currentUser?.userId}/${id}`, {
        method: 'DELETE'
      });
      if (res.ok) {
        toast.success("Course deleted successfully");
        fetchCourses();
      }
    } catch (error) {
      toast.error("Failed to delete course");
    }
  };

  const resetForm = () => {
    setIsEditing(null);
    reset(initialCourseState);
  };

  return (
    <div className="instructor-container">
      {currentUser?.role == 'instructor' ? (<>
        <div className="instructor-header">
          <h3>Instructor Dashboard</h3>
        </div>

        <div className="instructor-course-list">
          <h4>Your Courses</h4>
          {courses.map((course: Course) => (
            <div key={course.courseId} className="instructor-course-item">
              <div className="instructor-course-info">
                <img src={course.imageUrl} alt={course.name} className="instructor-course-img" />
                <div>
                  <h5>{course.name}</h5>
                  <p>Price: ${course.price} | Rating: {course.rating}</p>
                </div>
              </div>
              <div className="instructor-actions">
                <button className="btn btn-secondary" onClick={() => handleEdit(course)}>Edit</button>
                <button className="btn btn-danger" onClick={() => handleDelete(course.courseId)}>Delete</button>
              </div>
            </div>
          ))}
        </div> </>) : (<h3>You need Instructor rights to view this page.</h3>)}

        <form className="course-form" onSubmit={handleSubmit(onSubmit)}>
          <h4 style={{ gridColumn: 'span 2' }}>{isEditing ? 'Edit Course' : 'Add New Course'}</h4>
          <input
            placeholder="Course Name"
            {...register("name", { required: "Course Name is required" })}
          />
          {errors.name && <span className="error">{String(errors.name.message)}</span>}
          <input
            placeholder="Image URL"
            {...register("imageUrl", { required: "Image URL is required" })}
          />
          {errors.imageUrl && <span className="error">{String(errors.imageUrl.message)}</span>}
          <input
            placeholder="Duration (e.g. 3 months)"
            {...register("Duration", { required: "Duration is required" })}
          />
          {errors.Duration && <span className="error">{String(errors.Duration.message)}</span>}
          <input
            placeholder="Level"
            {...register("level", { required: "Level is required" })}
          />
          {errors.level && <span className="error">{String(errors.level.message)}</span>}
          <input
            placeholder="Price"
            {...register("price", { required: "Price is required" })}
          />
          {errors.price && <span className="error">{String(errors.price.message)}</span>}
          <input
            placeholder="Rating (0-5)"
            {...register("rating", { required: "Rating is required" })}
          />
          {errors.rating && <span className="error">{String(errors.rating.message)}</span>}
          <textarea
            placeholder="Description"
            {...register("description", { required: "Description is required" })}
            rows={4}
          />
          {errors.description && <span className="error">{String(errors.description.message)}</span>}

          <div className="chapters-form-section">
            <h4>Course Chapters & Videos</h4>
            {fields.map((field, index) => (
              <div key={field.id} className="chapter-input-group">
                <input
                  placeholder="Chapter Title"
                  {...register(`chapters.${index}.title` as const, { required: "Title required" })}
                />
                <input
                  placeholder="Duration (e.g. 10:00)"
                  {...register(`chapters.${index}.duration` as const, { required: "Duration required" })}
                />
                <input
                  placeholder="Video URL (YouTube/Video)"
                  {...register(`chapters.${index}.videoUrl` as const, { required: "Video URL required" })}
                />
                <button type="button" className="btn btn-danger" onClick={() => remove(index)}>Remove</button>
              </div>
            ))}
            <button
              type="button"
              className="btn btn-secondary"
              onClick={() => append({ title: '', duration: '', videoUrl: '' })}
            >
              + Add New Chapter
            </button>
          </div>

          <div className="form-actions">
            {isEditing && (
              <button type="button" className="btn btn-secondary" onClick={resetForm}>
                Cancel
              </button>
            )}
            <button type="submit" className="btn btn-primary">
              {isEditing ? 'Update Course' : 'Add Course'}
            </button>
          </div>
        </form>
    </div>
  );
}

export default InstructorCourses;